# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='i00t_tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_usuario', models.IntegerField()),
                ('co_estatus', models.IntegerField()),
                ('nb_tarea', models.CharField(max_length=50)),
                ('tx_descripcion', models.CharField(max_length=200)),
                ('ff_tarea', models.DateField()),
                ('in_activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='i00t_tareas_estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_estatus', models.CharField(max_length=50)),
                ('tx_descripcion', models.CharField(max_length=200)),
                ('in_activo', models.IntegerField()),
            ],
        ),
    ]
